# Generated by Django 4.2.26 on 2025-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=500)),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_students', models.IntegerField(default=0)),
                ('total_students_girls', models.IntegerField(default=0)),
                ('total_students_boys', models.IntegerField(default=0)),
                ('total_classes', models.IntegerField(default=0)),
                ('max_capacity', models.IntegerField(default=0)),
                ('real_capacity', models.IntegerField(default=0)),
                ('students_class_1', models.IntegerField(default=0)),
                ('students_class_2', models.IntegerField(default=0)),
                ('students_class_3', models.IntegerField(default=0)),
                ('students_class_4', models.IntegerField(default=0)),
                ('students_class_5', models.IntegerField(default=0)),
                ('students_class_6', models.IntegerField(default=0)),
                ('students_class_7', models.IntegerField(default=0)),
                ('students_class_8', models.IntegerField(default=0)),
                ('students_class_9', models.IntegerField(default=0)),
                ('students_class_10', models.IntegerField(default=0)),
                ('students_class_11', models.IntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('director_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_form', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Школа',
                'verbose_name_plural': 'Школы',
                'ordering': ['name'],
            },
        ),
    ]
